version: '3.2'

services:
  database:
    restart: always
    image: mysql:latest
    ports:
      - 3307:3306 # ローカルMySQLとの重複回避のため、ポート番号を変更
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-datavolume:
    driver: local
